config/routes.rb
Rails.application.routes.draw do
  
  get "/hello", to: "hello#index"
  resources :tareas
  resources :tasks
  
  root "tareas#index"
  
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tarea.rb
class Tarea < ApplicationRecord
    validates :descr, presence: true, length: { maximum: 200 }
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
    has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
  def index
  end
end

app/controllers/tareas_controller.rb
class TareasController < ApplicationController
  before_action :set_tarea, only: %i[show edit update destroy]

  # GET /tareas or /tareas.json
  def index
    @tareas = Tarea.all
    @tarea = Tarea.new
  end

  # GET /tareas/1 or /tareas/1.json
  def show
    
  end

  # GET /tareas/new
  def new
    @tarea = Tarea.new
  end

  # GET /tareas/1/edit
  def edit
  end

  # POST /tareas or /tareas.json
  def create
    @tarea = Tarea.new(tarea_params)

    respond_to do |format|
      if @tarea.save
        format.html do
          redirect_to root_url(@tarea), notice: "Task successfully created :)"
        end
        format.json { render :show, status: :created, location: @tarea }
      else
        format.html do
          redirect_to root_url(@tarea), alert: "Task can't be empty"
        end
        format.json do
          render json: @tarea.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # PATCH/PUT /tareas/1 or /tareas/1.json
  def update
    respond_to do |format|
      if @tarea.update(tarea_params)
        format.html do
          redirect_to root_url(@tarea), notice: "Task successfully updated"
        end
        format.json { render :show, status: :ok, location: @tarea }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json do
          render json: @tarea.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # DELETE /tareas/1 or /tareas/1.json
  def destroy
    @tarea.destroy

    respond_to do |format|
      format.html do
        redirect_to root_url(@tarea), notice: "Task successfully deleted"
      end
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_tarea
    @tarea = Tarea.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def tarea_params
    params.require(:tarea).permit(:descr, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/tareas_helper.rb
module TareasHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/hello/index.html.erb
<section class="section">
<h1 class="title" >Hello World!</h1>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render "tareas/navbar" %>
  <div class="container"> 
    
        <%= render "tareas/flash" %>
        
        <%= yield %>
  </div>
  </body>
</html>

app/views/tareas/_error.html.erb
<% if @tarea.errors.any? %>
  <% @tarea.errors.each do  %>
    <div class="notification is-danger is-light">
      <h1 class="title is-5"> Something went wrong:</h1>
      <ul>
        <% @tarea.errors.each do |error| %>
        <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

app/views/tareas/_flash.html.erb
<% flash.each do |type, msg| %>
  <% if notice %>
  <div class="notification is-success is-light">
    <%= msg %>
  </div>
  <% else %>
  <div class="notification is-danger is-light">
  <%= msg %>
</div>
<% end %>
<% end %>

app/views/tareas/_form.html.erb
<%= form_with(model: tarea) do |f| %>
  <form class="box">
  <div class="control">
        <div class="field">
            <%= f.text_field :descr, class: "input", placeholder: "New task" %>
            <%= f.submit "update", class: "button"  %>
        </div>
    
  </div>

  </form>

  
  </form>
<% end %>

app/views/tareas/_form_index.html.erb
<%= render "tareas/error" %>

<%= form_with(model: @tarea) do |f| %>
  
  <form class="box">
  <div class="control">
        <div class="field">
            <%= f.text_field :descr, class: "input", placeholder: "New task" %>
            <%= f.submit "add", class: "button"  %>
        </div>
    
  </div>

  </form>
<% end %>

app/views/tareas/_navbar.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
<%= link_to root_url do %>  
<div class="navbar-brand">
  
    <div class="navbar-item">
    <div>
      <i class="fa-solid fa-list-check fa-2xl"></i>
      
      </div>
    </div>
   
   
    <div class="navbar-item">
      <h1 class="title is-3">To do list</h1>
    </div>
 
  </div>
  <% end %>
    <div class="navbar-end">
    <div class="navbar-item">
    <h1 class="title is-5">made with Rails</h1>
    </div>
    </div>
</nav>

app/views/tareas/_tarea.html.erb
<div id="<%= dom_id tarea %>">
  <p>
    <strong>Descr:</strong>
    <%= tarea.descr %>
  </p>

  <p>
    <strong>Completed:</strong>
    <%= tarea.completed %>
  </p>

</div>

app/views/tareas/edit.html.erb
<section class="section">
  <h1 class="title"> Edit task</h1>
  
  <div class="box">
  <%= render "form", tarea: @tarea %>
  </div>
    <table class="table">
      <tbody>
        <tr>
          <td><%= link_to "Show this task", @tarea %> </td>
          <td><%= link_to "Back to all tasks", tareas_path %></td>
        </tr>
      </tbody>
    </table>
</section>

app/views/tareas/index.html.erb
<section class="section">
<div class="box">
<%= render "tareas/form_index" %>
</div>

<div class="box">
<% if @tareas.any? %>
<table class="table">
  <tbody>
    <% @tareas.each do |tarea| %>
    <tr>
      <% if tarea.completed %>
      <td><p class="completed"><%= tarea.descr %></p></td>
      <td>
      <center>
      <%=form_for(tarea) do |f| %>
        <%= f.text_field :descr, type: 'hidden'  %>
        <%= f.check_box :completed, :checked => false, :style => 'visibility: hidden'  %>
        <%= f.submit "✔︎", class: 'button is-light' %>
        <% end %>
        </center>
      </td>
 
      
      <% else %>
      <td><p><%= tarea.descr %></p></td>
      <td>
      <center>
      <%=form_for(tarea) do |f| %>
        <%= f.text_field :descr, type: 'hidden'  %>
        <%= f.check_box :completed, :checked => true, :style => 'visibility: hidden'  %>
        <%= f.submit "✔︎", class: 'button' %>
      <% end %>
      </center>
      </td>
      <% end %>
      
      <td>
        
          <%= link_to tarea do %>
          <i class="fa-solid fa-eye"></i>
          <%end%>
      </td>
      <td>
        
          <%= link_to edit_tarea_path(tarea) do %>
          <i class="fa-solid fa-pen"></i>
          <%end%>
      </td>
      <td>
      <%= link_to tarea, method: :delete, data: {
        turbo_method: :delete,
        turbo_confirm: "Are you sure?"
      } do %>  
        <i class="fa-solid fa-trash-can"></i>
      <%end%>
      </td>
    </tr>
   
  <% end %>
  </tbody>
</table>
<% else %>
<h1 class="title is-6">No tasks added yet</h1>

<% end %>

</div>


</section>

app/views/tareas/new.html.erb
<section class="section">

    <h1 class="title">New task</h1>
    <div class="box">
    <%= render "form", tarea: @tarea %>

    </div>
    <div>
      <button class="button">
        <%= link_to "Back to all my tasks", tareas_path %>
      </button>
  </div>
</section>

app/views/tareas/show.html.erb
<section class="section">
  <h1 class="title"> <%= @tarea.descr %> </h1>
  <h1 class="title is-6">Created at <%= @tarea.created_at %> </h1>
    <table class="table">
      <tbody>
        <tr>
        <td><%= link_to edit_tarea_path(@tarea) do %>
          <button class="button is-ghost">
          <i class="fa-solid fa-pen"></i>
          </button>
          <% end %>
        </td>
        <td><%= button_to @tarea, class: "button is-ghost", method: :delete do %>  
          <i class="fa-solid fa-trash-can"></i>
        <% end %>
        </td>
          <td><%= link_to tareas_path  do %>
            <button class="button is-ghost">
            <i class="fa-solid fa-left"></i>
            Back
            <button class="button is-ghost">
            <% end %>
            </td>
          
      </tr>
  


          
      </tbody>
    </table>
</section>